/*
 * This source file was generated by the Gradle 'init' task
 */
package blue.rose;

import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.concurrent.Worker;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import java.io.IOException;

public class App extends Application{
    private WebEngine engine;

    public static void main(String[] args) throws IOException{
        launch(args);
    }

    @Override
    public void start(Stage stage){
        WebView view = new WebView();
        engine = view.getEngine();
        engine.load(getClass().getResource("/Index.html").toExternalForm());
        
    }
}
